import turtle as trtl

painter = trtl.Turtle()

painter.speed(0)
painter.color('black')
painter.penup()
painter.right(270)
painter.forward(100)
painter.right(90)
painter.pendown()
painter.circle(100)
painter.right(90)
painter.forward(50)
painter.right(90)
painter.forward(50)
painter.right(180)
painter.penup()
painter.forward(100)
painter.right(180)
painter.pendown()
painter.forward(50)
painter.right(270)
painter.forward(300)
painter.right(50)
painter.forward(100)
painter.penup()
painter.right(180)
painter.forward(100)
painter.right(80)
painter.pendown()
painter.forward(100)
wn = trtl.Screen()
wn.mainloop()
